Add optional configuration arguments to build and run commands
HipsterBrown/xs-dev pull request #104
Opened 2023-02-15 23:29 UTC by andycarle

This PR addresses issue #101. 

It implements the last suggestion by @phoddie, allowing `--config.ssid=MyWiFi` and `--config.password="a secret"`.

The change to add `shell: true` to the call to `system.exec` was necessary to preserve quotes around configuration items on Windows without weird escaping issues.

I welcome suggestions from TypeScript experts on how to better accomplish this while still keeping the linter happy 😆: 

```typescript
configArgs.push(`${element}="${config[element as keyof typeof config] as string}"`)`
```

2023-02-21 15:38 UTC, phoddie commented
Anything we can do to move this along? If we can get this merged, it will be another step towards parity with xs-dev and mcconfig, and would let our intern finish up his xs-dev video tutorial. Thanks.

2023-02-22 15:39 UTC, HipsterBrown requested changes
Thanks for adding this! Can you also include some documentation about this new flag?

2023-02-22 15:39 UTC, HipsterBrown commented on src/commands/build.ts
> +  config?: object
```suggestion
  config?: Record<string, string>
```

By using the [Record utility type](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type), we can specify the value type in the `config` object.

2023-02-22 15:39 UTC, HipsterBrown commented on src/toolbox/build/index.ts
> +  })
Using [`Object.entries`](http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries), we can get the key and value as part of the `forEach` iterator:

```suggestion
  Object.entries(config).forEach(([element, value]) => {
    configArgs.push(`${element}="${value}"`)
  })
```

2023-02-22 22:09 UTC, andycarle commented
@HipsterBrown: As usual, you win at TypeScript. 😄 I've made the changes you suggested (and in the related spots) and added a documentation entry for the `--config` flag.

2023-02-22 22:20 UTC, HipsterBrown approved these changes
LGTM! Thanks for adding this. Looking forward to the video tutorial from the Moddable team 😄

2023-02-22 22:20 UTC, merged

2023-02-22 22:40 UTC, andycarle commented
Thanks!

2023-02-22 23:36 UTC, andycarle commented
@HipsterBrown If you wouldn't mind spinning a release at your convenience, that would help Daniel with the video effort. Thanks!

2023-02-23 00:19 UTC, HipsterBrown commented
@andycarle @phoddie This feature has been released in v0.22.0 of the CLI. Thanks for your patience 👍 

I really need to start looking into automated releases given the growing contributions 🙌