Add TypeScript usage example
HipsterBrown/xs-dev pull request #187
Opened 2024-11-18 14:49 UTC by ScreamZ

2024-11-18 17:02 UTC, HipsterBrown requested changes
Thanks for creating this guide @ScreamZ 👏 

I've added a few comments and suggestions to make sure what's being documented is accurate and as seamless as possible for getting started. 

I think this will be a very good starting point for many TypeScript devs. :smile:

2024-11-18 17:02 UTC, HipsterBrown commented on docs/src/content/docs/guide/usage-with-typescript.mdx
> +  As modules from ModdableSDK are not available inside node_modules and injected
nit: missing space

```suggestion
  As modules from the Moddable SDK are not available inside node_modules and injected
```

2024-11-18 19:42 UTC, ScreamZ commented on docs/src/content/docs/guide/usage-with-typescript.mdx
> +A moddable project should ideally lives within a single file. This is because the Moddable SDK does not support the `import` and `export` keywords. This means that you will need to use a bundler to c
Yes, I get it better now. What I wanted to write was that if you don't use a bundler, as there is no relative file-system (as far as i understand what's going on), you need to declare things in `manifest.json` to allows mcpack to found those deps, which is a bit strange coming from a Web background. I'll try to improve this paragraph taking in consideration your notes. And submit changes. (thanks for reviewing !)

Two side notes
- I should read `mcpack` doc in detail, I've skipped the doc about it too much I guess.
- This is really sad that https://github.com/phoddie/node-cron and other things like these aren't indexed somewhere, this is pure gold. Maybe we could push them to my newly claimed `@embedded-js` org on npm ? What do you think ?

2024-11-18 19:48 UTC, ScreamZ commented on docs/src/content/docs/guide/usage-with-typescript.mdx
> +git clone git@github.com:ScreamZ/xs-dev-Typescript-template.git
Sounds an exciting tool ! Wasn't aware of its existence ! Do you think suggesting it through `bunx` is relevant here? Maybe `npx` would be more familial to dummies ?

2024-11-18 19:52 UTC, ScreamZ commented on docs/src/content/docs/guide/usage-with-typescript.mdx
> +The starter exposes a `pnpm dev` command that watch for changes in the `src` folder and automatically recompile the code. This is very useful when you are developing your project. You should keep thi
I don't know… What's really nice with `pnpm` is that they bring this shared store that reduce size on disk. This is also a widely adopted and mature tool.

But there are still many users on yarn 1, (not many on yarn berry, as its basically a fail on doing what pnpm achieved)

Some are trying bun package manager, it's nice but still bun is relatively new.

IMO, I would apply on adding pnpm. this is not a bad choice and a drop-in replacement for npm.

2024-11-20 15:25 UTC, HipsterBrown requested changes
A few more suggested updates and questions, otherwise it's looking ready to go!

2024-11-20 15:25 UTC, HipsterBrown commented on docs/src/content/docs/guide/usage-with-typescript.mdx
> +Using [TypeScript](https://www.typescriptlang.org/) is a industry standard in 2024. It provides a lot of benefits over JavaScript, such as static type checking, better code completion, and improved c
```suggestion
Using [TypeScript](https://www.typescriptlang.org/) is an industry standard in 2024. It provides a lot of benefits over JavaScript, such as static type checking, better code completion, and improved code readability. This guide will show you how to use TypeScript with the Moddable SDK.
```

2024-11-20 15:25 UTC, HipsterBrown commented on docs/src/content/docs/guide/usage-with-typescript.mdx
> +Otherwise follow the instructions on the [Bun website](https://bun.sh/).
To help with readability, we should display the mise install command after the sentence "you can install it with the following command:"

~~~suggestion
For this guide, as the bundler we will use [Bun](https://bun.sh/), which is a JavaScript Environment, but also a bundler/transpiler. It is a very simple tool that allows you to write your code in TypeScript and bundle it into a single file. If you use [mise-en-place](https://mise.jdx.dev/getting-started.html), you can install it with the following command:

```bash
mise install bun
```

Otherwise follow the instructions on the [Bun website](https://bun.sh/).

Along with Bun, we will add Typescript as a dev dependency because bundler for performances reasons do not lint the code. Therefore we will use `tsc` for that.
~~~

I don't see any instructions for adding TypeScript as a dev dependency. If you're referring to the starter template including TypeScript as a dev dependency, we should be specific about that.

2024-11-20 15:25 UTC, HipsterBrown commented on docs/src/content/docs/guide/usage-with-typescript.mdx
> +  a new project from a template.
`tiged` is the CLI that wraps around `git clone`, while `bunx` allows for running package commands without globally installing said package (similar to `npx`, `pnpx`, and `yarn dlx`.

2024-11-20 15:25 UTC, HipsterBrown commented on docs/src/content/docs/guide/usage-with-typescript.mdx
> +The first thing you need to do is to update the `package.json` file with your project details. You can do this by running the following command:
Is there a command to run? Or just a set of instructions?

2024-11-20 15:25 UTC, HipsterBrown commented on docs/src/content/docs/guide/usage-with-typescript.mdx
> +When you need to try the code, simply run `xs-dev run` in the terminal. This will upload the bundled code from `dist/main.js` to the device and run it. The rest remain the same as the standard xs-dev
nit: grammar

```suggestion
When you need to try the code, simply run `xs-dev run` in the terminal. This will upload the bundled code from `dist/main.js` to the device and run it. The rest remains the same as the standard xs-dev workflow.
```

2024-11-20 15:25 UTC, HipsterBrown commented on docs/src/content/docs/guide/usage-with-typescript.mdx
> +Those typings are provided by [`@moddable/typings` package](https://github.com/Moddable-OpenSource/moddable/tree/4142d4d353960ea7ede15d56864d841de692a68d/typings), and while at the moment this get a
```suggestion
Those typings are provided by [`@moddable/typings` package](https://github.com/Moddable-OpenSource/moddable/tree/4142d4d353960ea7ede15d56864d841de692a68d/typings), and while at the moment this is a bit cumbersome, it's up to you to find the correct definition file for the module you are using.
```

2024-11-20 15:25 UTC, HipsterBrown commented on docs/src/content/docs/guide/usage-with-typescript.mdx
> +As an example Timer and WiFi lives in `./node_modules/@moddable/typings/wifi` and `./node_modules/@moddable/typings/timer`
```suggestion
As an example, the Timer and WiFi modules live in `./node_modules/@moddable/typings/wifi` and `./node_modules/@moddable/typings/timer`
```

2024-11-20 15:56 UTC, ScreamZ commented on docs/src/content/docs/guide/usage-with-typescript.mdx
> +The first thing you need to do is to update the `package.json` file with your project details. You can do this by running the following command:
this is a set of instructions now, forgot to update after the removal of things in favor of tiged

2024-11-20 16:00 UTC, ScreamZ commented
Looks ready for final review

2024-11-20 16:54 UTC, HipsterBrown approved these changes
Thanks again for contributing this guide!

2024-11-20 16:55 UTC, merged