feat: Windows setup extension start (#23)
HipsterBrown/xs-dev pull request #44
Opened 2022-04-02 04:32 UTC by andycarle

Start of Windows setup extension. 

To-Do:
- Setting reasonable default paths for Windows in `constants.ts`
- Automatic setup of vs.bat environment?
- Some tidying

2022-04-03 17:34 UTC, HipsterBrown requested changes
Thank you again for tackling this work! Most of the suggested changes are related to matching the style of the other modules in this repo. I'm excited to see this tested in the wild :clap:

2022-04-03 17:34 UTC, HipsterBrown commented on src/toolbox/setup/windows.ts
> +}
Using the typed version of the `regedit` package, we are provided types for a valid RegistryItemValue: 

```ts
import type { RegistryItemValue } from 'regedit'
```

[Reference types](https://github.com/ironSource/node-regedit/blob/master/regedit.d.ts#L1-L36)

2022-04-03 17:34 UTC, HipsterBrown commented on src/toolbox/setup/windows.ts
> +}
I don't think we need a `Result` type since we're using Promises, so we can lean into the `try...catch` control flow around the result of this async function. It also appears the `result` value from reading the environment variables is unused, so we can remove that logic from the top of the function. The `reg` variable is also updated to use the `RegistryItemPutCollection` from `regedit`. 


```suggestion
async function setEnv(name: string, value: RegistryItemValue): Promise<void> {
  try {
    const reg: RegistryItemPutCollection = {
      'HKCU\\ENVIRONMENT': {
        [name]: value,
      },
    }
    await regedit.putValue(reg)
  } catch (error) {
    throw new Error('Error while saving environment variable to registry')
  }
}
```

2022-04-03 17:34 UTC, HipsterBrown commented on src/toolbox/setup/windows.ts
> +}
By leaning into the linter and type feedback, we can see that the `if (result)` check is not required because it cannot exist past the `try...catch` block due to the early return (or thrown error as suggested in this refactor). 

The type feedback also enforces from checks about the result of the Path environment value. So the `tokens` variable ensures the `pathEnv` type is `REG_EXPAND_SZ` before splitting the string value, otherwise falls back to an empty array. The `found` variable logic can also be replaced by the [`some` array method](http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some). 

The last notable suggested refactor is reusing the `setEnv` function above for setting the PATH env variable. Since `setEnv` provides some useful Error messaging, we can remove the `try...catch` around the PATH setting.

```suggestion
async function addToPath(BIN_PATH: string): Promise<string> {
  let result
  try {
    result = await regedit.list([`HKCU\\ENVIRONMENT`])
  } catch (error) {
    throw new Error('Error while reading User Path from registry')
  }

  const pathEnv = result['HKCU\\ENVIRONMENT'].values.Path
  const tokens =
  pathEnv.type === 'REG_EXPAND_SZ' ? pathEnv.value.split(';') : []
  const moddableExists = tokens.some((token) => token === BIN_PATH)

  if (moddableExists) {
    return 'Moddable BIN already in User PATH.'
  } else {
    await setEnv('PATH', {
      value: `${tokens.join(';')};${BIN_PATH}`,
      type: 'REG_EXPAND_SZ',
    })
    return 'Moddable BIN now set in PATH.'
  }
}
```

2022-04-03 17:34 UTC, HipsterBrown commented on src/toolbox/setup/windows.ts
> +  }
We can use [gluegun's `system.which`](https://infinitered.github.io/gluegun/#/toolbox-system?id=toolboxsystemwhich) to see if the command exists:

```suggestion
    if (system.which('nmake') === null) {
    print.error(
      'Visual Studio 2022 Community is required to build the Moddable SDK: https://www.visualstudio.com/downloads/'
    )
    // @@TODO: need to check if perhaps VS.bat has not been run...
    process.exit(1)
  }
```

2022-04-03 17:34 UTC, HipsterBrown commented on src/toolbox/setup/windows.ts
> +  }
Same comment about using `system.which`:

```suggestion
  if (system.which('git') === null) {
    print.error(
      'git is required to clone the Moddable SDK: https://git-scm.com/download/win'
    )
    process.exit(1)
  }
```

2022-04-03 17:34 UTC, HipsterBrown commented on src/toolbox/setup/windows.ts
> +    await upsert(EXPORTS_FILE_PATH, `# Generated by xs-dev CLI`)
Should this `EXPORTS_FILE_PATH` be updated or replaced by a Window's specific path to a batch file instead of a shell file extension?

2022-04-03 17:34 UTC, HipsterBrown commented on src/toolbox/setup/windows.ts
> +  }
With the suggested refactor to `setEnv`, we can replace the `if` checks with `try..catch`:

```suggestion
  try {
    await setEnv('MODDABLE', {
      value: INSTALL_PATH,
      type: 'REG_SZ',
    })
    spinner.succeed()
  } catch (error) {
    spinner.fail(error.toString())
  }
```

2022-04-03 17:34 UTC, HipsterBrown commented on src/toolbox/setup/windows.ts
> +  }
With the suggested refactor to `addToPath`:

```suggestion
  try {
    const result = await addToPath(BIN_PATH)
    spinner.info(result)
    spinner.succeed()
  } catch (error) {
    spinner.fail(error.toString())
  }
```

2022-04-04 22:32 UTC, andycarle commented
@HipsterBrown Thank you for the thoughtful review! This is my first foray into non-trivial TypeScript, so I'm learning a lot here.

I'll take a pass on this today and see what I come up with.

2022-04-04 23:10 UTC, andycarle commented on src/toolbox/setup/windows.ts
> +    await upsert(EXPORTS_FILE_PATH, `# Generated by xs-dev CLI`)
`EXPORTS_FILE_PATH` can be removed entirely, at least for now. It may come back when I look at ESP32.

2022-06-21 07:22 UTC, andycarle commented
Hi @HipsterBrown!

I'm hoping to prioritize Windows support for xs-dev over the next couple of weeks. The new commits above (which of course would need to be squashed down... a lot... before merging) are a start. On my system, `xs-dev setup` and `xs-dev update` are now working well.

There may still need to be some updates to the defaults in `constants.ts` to make it make a bit more sense on Windows. But I am not sufficiently confident in where people prefer tools like this to reside on Windows to make the change right now. I'll do a bit of research there.

I'm going to take a crack at initial ESP8266 and ESP32 support next.

2022-06-21 14:39 UTC, HipsterBrown commented
> On my system, xs-dev setup and xs-dev update are now working well.

@andycarle that's great! To keep the amount of changes per pull request manageable, how do you feel about splitting the ESP8266 and ESP32 work into separate PRs? 

Once we get the build checks complete (looks like I need to update those workflow files on `main`), then I'm open to approving and merging this set of changes in.

2022-06-21 14:50 UTC, HipsterBrown requested changes

2022-06-21 14:50 UTC, HipsterBrown commented on package.json
> +    "regedit": "ironSource/node-regedit#f9df4db824fe68ec3b11e33af987ec42a2eeec32",
It looks like this package has been updated to publish types with the latest releases since the last review of this PR 🙌 

```suggestion
    "regedit": "5.1.1",
```

2022-07-01 19:41 UTC, andycarle commented
Yes, I agree that we can split the ESP8266 and ESP32 work out to another PR. I'm getting started on those today. 

I'm also double-checking some things around PATH management in this PR. I'm concerned about the possibility of the PATH being corrupted in some edge cases—I'll get that sorted out.

2022-07-20 01:58 UTC, andycarle commented
This PR is superseded by #53, which takes a cleaner approach to environment management.

2022-07-20 01:58 UTC, closed without merging